name: CI/CD
on: workflow_dispatch
jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      # Récupération du code source
      - name: Checkout du code
        uses: actions/checkout@v6
      # Installation de PHP
      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: 'intl, pdo_pgsql, redis'
          tools: 'composer:v2'
      # Cache des dépendances Composer
      - name: Cache Composer
        uses: actions/cache@v5
        with:
          path: 'vendor'
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-
      # Installation des dépendances
      - name: Installation des dépendances
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist
      - name: Linting du code avec PHP CS FIXER
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Linting du code avec PHPStan
        run: vendor/bin/phpstan analyse

    # ===========================================================================
    # Job : Vérification de la qualité du code JavaScript
    # ===========================================================================
  lint-frontend:
    name: Lint Frontend (JS)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout du code
        uses: actions/checkout@v6

      # --- Installer Node.js ---
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      # --- Mettre en cache les dépendances npm ---
      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('front/package-lock.json') }}
          restore-keys: npm-

      - name: Installation des dépendances
        run: npm ci

      # --- Vérifier la qualité du code ---
      - name: ESLint
        run: npm run lint